### ISSUE TITLE
Update Developer Guide

### ISSUE THREAD

**Issue by colintkn** [AY2021S2-CS2103-T14-1/tp#102]
Each member should describe the implementation of at least one enhancement she has added (or planning to add).
Expected length: 1+ page per person
The description can contain things such as,
How the feature is implemented (or is going to be implemented).
Why it is implemented that way.
Alternatives considered.

**Comment by benedictkhoomw** [comment]
We may want to break this up into at least 5 separate issues since each member is expected to update the DG. That way, each member can close the relevant issue when they are done with their part.

Further, I suggest we break up DG update issues by feature, rather than by team member because a DG update per feature seems like a more correctly-sized unit of work than a DG update per team member or one monolithic update consisting of everyone's updates.

**Comment by benedictkhoomw** [comment]
Split into 5 separate issues that can be closed individually by each member.
